In [3]:
import gym
import numpy as np 

# 1. Load Environment and Q-table structure
env = gym.make('FrozenLake8x8-v1')
Q = np.zeros([env.observation_space.n,env.action_space.n])
# env.observation.n, env.action_space.n gives number of states and action in env loaded

# 2. Parameters of Q-learning
eta = .628
gma = .9
epis = 5000
rev_list = [] # rewards per episode calculate

# 3. Q-learning Algorithm
for i in range(epis):
    # Reset environment
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
#         env.render()
        j+=1
        # Choose action from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state & reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rev_list.append(rAll)
#     env.render()

print("Reward Sum on all episodes " + str(sum(rev_list)/epis))
print("Final Values Q-Table")
print(Q)

Reward Sum on all episodes 0.2178
Final Values Q-Table
[[2.19895425e-03 1.88201146e-03 2.01879365e-03 5.10393463e-03]
 [1.81824452e-03 1.17416216e-03 9.15800901e-03 1.98907839e-03]
 [1.27055134e-03 2.38970359e-03 1.24191135e-02 1.83215839e-03]
 [2.16046264e-03 1.92698333e-03 9.91172445e-03 1.90614740e-03]
 [1.18475853e-03 2.42943286e-03 1.62810902e-02 1.79487564e-03]
 [2.15138259e-03 0.00000000e+00 2.64022630e-02 2.04807179e-03]
 [0.00000000e+00 0.00000000e+00 5.20709014e-02 0.00000000e+00]
 [2.20166211e-03 4.33670918e-02 2.91974594e-03 0.00000000e+00]
 [1.77939680e-03 3.21493839e-03 1.80546561e-03 1.81083957e-03]
 [1.44275129e-03 1.97532658e-03 1.47687487e-03 5.61497639e-03]
 [1.48624970e-03 1.76855421e-03 1.14443769e-03 1.13802644e-02]
 [3.07038435e-04 7.08551857e-04 1.98435188e-04 1.07353942e-02]
 [2.60126751e-03 9.95657990e-04 1.94746248e-03 2.59562397e-02]
 [1.97606799e-03 1.73512448e-03 2.82596950e-02 3.29792562e-03]
 [3.33239093e-03 6.59579722e-02 0.00000000e+00 0.00000000e+00]
